### ISSUE TITLE
JavaALSSuite in error due to UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by sonia-garudi** [OpenPOWER-BigData/HDP-spark#1]
Failed Project: Spark Project ML Library

Tests in error: 
  JavaALSSuite.runALSUsingConstructor:115 ? UnsatisfiedLink org.jblas.NativeBlas...
  JavaALSSuite.runALSUsingStaticMethods:101 ? UnsatisfiedLink org.jblas.NativeBl...

Stacktrace:

-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /ws/spark-release/mllib/target/tmp/jblas6615862881587420348/libjblas.so: libgfortran.so.3: cannot open shared object file: No such file or directory.

runALSUsingStaticMethods(org.apache.spark.mllib.recommendation.JavaALSSuite)  Time elapsed: 0.303 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: org.jblas.NativeBlas.dgemm(CCIIID[DII[DIID[DII)V
    at org.jblas.NativeBlas.dgemm(Native Method)
    at org.jblas.SimpleBlas.gemm(SimpleBlas.java:247)
    at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1781)
    at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3138)
    at org.apache.spark.mllib.recommendation.ALSSuite$.generateRatings(ALSSuite.scala:74)
    at org.apache.spark.mllib.recommendation.ALSSuite$.generateRatingsAsJavaList(ALSSuite.scala:40)
    at org.apache.spark.mllib.recommendation.ALSSuite.generateRatingsAsJavaList(ALSSuite.scala)
    at org.apache.spark.mllib.recommendation.JavaALSSuite.runALSUsingStaticMethods(JavaALSSuite.java:101)

runALSUsingConstructor(org.apache.spark.mllib.recommendation.JavaALSSuite)  Time elapsed: 0.199 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: org.jblas.NativeBlas.dgemm(CCIIID[DII[DIID[DII)V
    at org.jblas.NativeBlas.dgemm(Native Method)
    at org.jblas.SimpleBlas.gemm(SimpleBlas.java:247)
    at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1781)
    at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3138)
    at org.apache.spark.mllib.recommendation.ALSSuite$.generateRatings(ALSSuite.scala:74)
    at org.apache.spark.mllib.recommendation.ALSSuite$.generateRatingsAsJavaList(ALSSuite.scala:40)
    at org.apache.spark.mllib.recommendation.ALSSuite.generateRatingsAsJavaList(ALSSuite.scala)
    at org.apache.spark.mllib.recommendation.JavaALSSuite.runALSUsingConstructor(JavaALSSuite.java:115)

**Comment by sonia-garudi** [comment]
This issue is reproducible on x86 as well. 

The error is occuring because libgfortran3 is not installed. 
Found an issue logged for this error at https://spark-project.atlassian.net/browse/SPARK-797
